### ISSUE TITLE
Operator fails with a panic on MongoDB ReplicaSet update

### ISSUE THREAD

**Issue by legal90** [kubedb/project#434]
Hi! 

I'm using kubedb v0.9.0 deployed from the official Helm chart with default values (https://kubedb.com/docs/0.9.0/setup/install/)

I have a sample MongoDB created with `replica: 1`:
```
apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  finalizers:
  - kubedb.com
  generation: 4
  name: kubedb-mongodb
  namespace: pritunl
  resourceVersion: "8701010"
  selfLink: /apis/kubedb.com/v1alpha1/namespaces/pritunl/mongodbs/kubedb-mongodb
  uid: 44cc6d76-3073-11e9-907b-121086f294a4
spec:
  databaseSecret:
    secretName: kubedb-mongodb-auth
  podTemplate:
    controller: {}
    metadata: {}
    spec:
      livenessProbe:
        exec:
          command:
          - mongo
          - --eval
          - db.adminCommand('ping')
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        exec:
          command:
          - mongo
          - --eval
          - db.adminCommand('ping')
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources: {}
  replicas: 1
  serviceTemplate:
    metadata:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
    spec:
      ports:
      - name: db
        port: 27017
      type: LoadBalancer
  storage:
    accessModes:
    - ReadWriteOnce
    dataSource: null
    resources:
      requests:
        storage: 10Gi
    storageClassName: gp2
  storageType: Durable
  terminationPolicy: DoNotTerminate
  updateStrategy:
    type: RollingUpdate
  version: 3.6-v1
status:
  observedGeneration: 4$6211945921239001045
  phase: Running
```

If I edit this object and try enabling replicaset by increasing `spec.replicas` to `3` and adding `spec.replicaSet.name: rs0`, e.q.
```
spec:
  replicas: 3
  replicaSet:
    name: rs0
```
... the `kubectl edit` command fails with this output:
```
error: mongodbs.kubedb.com "kubedb-mongodb" could not be patched: Internal error occurred: failed calling admission webhook "mongodb.validators.kubedb.com": the server is currently unable to handle the request
```
and then I see that kudedb pod crashed with this output (and got restarted):
```
E0218 13:26:22.259540       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/go/src/github.com/kubedb/operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/go/src/github.com/kubedb/operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/github.com/kubedb/operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:522
/usr/local/go/src/runtime/panic.go:513
/usr/local/go/src/runtime/panic.go:82
/usr/local/go/src/runtime/signal_unix.go:390
/go/src/github.com/kubedb/operator/vendor/github.com/kubedb/mongodb/pkg/admission/validator.go:114
/go/src/github.com/kubedb/operator/pkg/server/server.go:186
/go/src/github.com/kubedb/operator/vendor/github.com/appscode/kubernetes-webhook-util/registry/admissionreview/v1beta1/admission_review.go:45
/go/src/github.com/kubedb/operator/vendor/k8s.io/apiserver/pkg/endpoints/handlers/create.go:189
/go/src/github.com/kubedb/operator/vendor/k8s.io/apiserver/pkg/endpoints/handlers/create.go:133
/go/src/github.com/kubedb/operator/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:185
/usr/local/go/src/runtime/asm_amd64.s:1333
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1d79219]

goroutine 5132 [running]:
github.com/kubedb/operator/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0xc001019f78, 0x1, 0x1)
	/go/src/github.com/kubedb/operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x108
panic(0x20d8540, 0x54f7a70)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/kubedb/operator/vendor/github.com/kubedb/mongodb/pkg/admission.(*MongoDBValidator).Admit(0xc00008e540, 0xc00119edc0, 0x0)
	/go/src/github.com/kubedb/operator/vendor/github.com/kubedb/mongodb/pkg/admission/validator.go:114 +0x6d9
github.com/kubedb/operator/vendor/github.com/appscode/kubernetes-webhook-util/admission/v1beta1.AdmissionHook.Admit-fm(0xc00119edc0, 0x0)
	/go/src/github.com/kubedb/operator/pkg/server/server.go:186 +0x39
github.com/kubedb/operator/vendor/github.com/appscode/kubernetes-webhook-util/registry/admissionreview/v1beta1.(*REST).Create(0xc00000cb38, 0x3dac180, 0xc0010edf80, 0x3d86180, 0xc000da8180, 0x24e0388, 0xc000ac2740, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/kubedb/operator/vendor/github.com/appscode/kubernetes-webhook-util/registry/admissionreview/v1beta1/admission_review.go:45 +0x4c
github.com/kubedb/operator/vendor/k8s.io/apiserver/pkg/endpoints/handlers.(*namedCreaterAdapter).Create(0xc000ec8b70, 0x3dac180, 0xc0010edf80, 0x0, 0x0, 0x3d86180, 0xc000da8180, 0x24e0388, 0xc000ac2740, 0x3d80240, ...)
	/go/src/github.com/kubedb/operator/vendor/k8s.io/apiserver/pkg/endpoints/handlers/create.go:189 +0x7f
github.com/kubedb/operator/vendor/k8s.io/apiserver/pkg/endpoints/handlers.createHandler.func1.1(0xc000000018, 0x24e0048, 0xc000681f78, 0x1)
	/go/src/github.com/kubedb/operator/vendor/k8s.io/apiserver/pkg/endpoints/handlers/create.go:133 +0x135
github.com/kubedb/operator/vendor/k8s.io/apiserver/pkg/endpoints/handlers.finishRequest.func1(0xc000aa3740, 0xc000e03b20, 0xc000aa3680, 0xc000aa3560)
	/go/src/github.com/kubedb/operator/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:185 +0x94
created by github.com/kubedb/operator/vendor/k8s.io/apiserver/pkg/endpoints/handlers.finishRequest
	/go/src/github.com/kubedb/operator/vendor/k8s.io/apiserver/pkg/endpoints/handlers/rest.go:178 +0xd4
```

The issue is persistent - kubedb operator crashes every time I try to edit this MongoDB object.
Simple patching (like adding a `metadata.annotations` elements) works file

**Comment by the-redback** [comment]
It is not allowed to change a standalone instance to replicaset. But, Panic is not expected. 
Anyway, refactorization in master have solved this panic already. https://github.com/kubedb/mongodb/blob/41f34809e8f1a5151b7138083d49f449bdf4c602/pkg/admission/validator.go#L113-L114
