### ISSUE TITLE
KubeDB Community for SSL tests

### ISSUE THREAD

**Issue by hossainemruz** [kubedb/project#811]
**Operator:**
```bash
❯ kubectl get pod -n kube-system  | grep kubedb-community
kubedb-community-7cf7dc947c-qp29v            0/1     CrashLoopBackOff   9          27h
```

```bash
panic: MongoDB mongodb-2twn5d/mongodb-3d4wmu is missing tls spec

goroutine 895 [running]:
kubedb.dev/apimachinery/apis/kubedb/v1alpha2.(*MongoDB).MustCertSecretName(0xc00013bd40, 0x34eca82, 0x6, 0x0, 0x0, 0xc00003a000, 0x30ce400)
        /src/vendor/kubedb.dev/apimachinery/apis/kubedb/v1alpha2/mongodb_helpers.go:655 +0x473
kubedb.dev/mongodb/pkg/controller.(*Controller).GetMongoDBClientOpts(0xc0008a2000, 0xc00013bd40, 0xc000fe14c0, 0x37, 0xc0022fe9d0, 0x4, 0xc0005f3128)
        /src/vendor/kubedb.dev/mongodb/pkg/controller/health.go:253 +0x319
kubedb.dev/mongodb/pkg/controller.(*Controller).GetMongoClient(0xc0008a2000, 0xc00013bd40, 0xc000fe14c0, 0x37, 0x1, 0xc000fe14c0, 0x37)
        /src/vendor/kubedb.dev/mongodb/pkg/controller/health.go:227 +0x4d
kubedb.dev/mongodb/pkg/controller.(*Controller).CheckMongoDBHealth.func1.1(0xc002374b60, 0xc00013bd40, 0xc0008a2000)
        /src/vendor/kubedb.dev/mongodb/pkg/controller/health.go:75 +0x10ca
created by kubedb.dev/mongodb/pkg/controller.(*Controller).CheckMongoDBHealth.func1
        /src/vendor/kubedb.dev/mongodb/pkg/controller/health.go:66 +0x166
```

**MongoDB:**
```yaml
apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  creationTimestamp: "2021-01-07T12:07:48Z"
  finalizers:
  - kubedb.com
  generation: 2
  labels:
    app: mongodb-e2e-ajepld
  name: mongodb-3d4wmu
  namespace: mongodb-2twn5d
  resourceVersion: "166818"
  selfLink: /apis/kubedb.com/v1alpha2/namespaces/mongodb-2twn5d/mongodbs/mongodb-3d4wmu
  uid: bf071eb9-d95a-4cce-a15f-436f711281d7
spec:
  authSecret:
    name: mongodb-3d4wmu-auth
  podTemplate:
    controller: {}
    metadata: {}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: mongodb-3d4wmu
                  app.kubernetes.io/managed-by: kubedb.com
                  app.kubernetes.io/name: mongodbs.kubedb.com
              namespaces:
              - mongodb-2twn5d
              topologyKey: kubernetes.io/hostname
            weight: 100
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: mongodb-3d4wmu
                  app.kubernetes.io/managed-by: kubedb.com
                  app.kubernetes.io/name: mongodbs.kubedb.com
              namespaces:
              - mongodb-2twn5d
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 50
      livenessProbe:
        exec:
          command:
          - bash
          - -c
          - "set -x; if [[ $(mongo admin --host=localhost --tls --tlsCAFile=/var/run/mongodb/tls/ca.crt
            --tlsCertificateKeyFile=/var/run/mongodb/tls/client.pem --username=$MONGO_INITDB_ROOT_USERNAME
            --password=$MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase=admin
            --quiet --eval \"db.adminCommand('ping').ok\" ) -eq \"1\" ]]; then \n
            \         exit 0\n        fi\n        exit 1"
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        exec:
          command:
          - bash
          - -c
          - "set -x; if [[ $(mongo admin --host=localhost --tls --tlsCAFile=/var/run/mongodb/tls/ca.crt
            --tlsCertificateKeyFile=/var/run/mongodb/tls/client.pem --username=$MONGO_INITDB_ROOT_USERNAME
            --password=$MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase=admin
            --quiet --eval \"db.adminCommand('ping').ok\" ) -eq \"1\" ]]; then \n
            \         exit 0\n        fi\n        exit 1"
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 1Gi
      serviceAccountName: mongodb-3d4wmu
  replicas: 1
  sslMode: requireSSL
  storage:
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
  storageEngine: wiredTiger
  storageType: Durable
  terminationPolicy: Halt
  version: 4.2.3
status:
  conditions:
  - lastTransitionTime: "2021-01-07T12:07:48Z"
    message: 'The KubeDB operator has started the provisioning of MongoDB: mongodb-2twn5d/mongodb-3d4wmu'
    reason: DatabaseProvisioningStartedSuccessfully
    status: "True"
    type: ProvisioningStarted
  - lastTransitionTime: "2021-01-07T12:07:49Z"
    message: 'All desired replicas are not ready. For StatefulSet: mongodb-2twn5d/mongodb-3d4wmu
      desired replicas: 1, ready replicas: 0.'
    reason: SomeReplicasNotReady
    status: "False"
    type: ReplicaReady
  observedGeneration: 1
  phase: Provisioning
```

**Comment by hossainemruz** [comment]
Operator shouldn't crash because of any miss-configuration in the database object.

**Comment by hossainemruz** [comment]
```bash
panic: MongoDB mongodb-pmvsa6/mongodb-mongodb-e2e-t6qtjc is missing secret name for client certificate

goroutine 725 [running]:
kubedb.dev/apimachinery/apis/kubedb/v1alpha2.(*MongoDB).MustCertSecretName(0xc0004fbb00, 0x34eca82, 0x6, 0x0, 0x0, 0x0, 0x0)
        /src/vendor/kubedb.dev/apimachinery/apis/kubedb/v1alpha2/mongodb_helpers.go:665 +0x353
kubedb.dev/mongodb/pkg/controller.(*Controller).GetMongoDBClientOpts(0xc000161200, 0xc0004fbb00, 0xc000931130, 0x4f, 0xc002452ac0, 0x4, 0xc00013b128)
        /src/vendor/kubedb.dev/mongodb/pkg/controller/health.go:253 +0x319
kubedb.dev/mongodb/pkg/controller.(*Controller).GetMongoClient(0xc000161200, 0xc0004fbb00, 0xc000931130, 0x4f, 0x1, 0xc000931130, 0x4f)
        /src/vendor/kubedb.dev/mongodb/pkg/controller/health.go:227 +0x4d
kubedb.dev/mongodb/pkg/controller.(*Controller).CheckMongoDBHealth.func1.1(0xc002452af0, 0xc0004fbb00, 0xc000161200)
        /src/vendor/kubedb.dev/mongodb/pkg/controller/health.go:75 +0x10ca
created by kubedb.dev/mongodb/pkg/controller.(*Controller).CheckMongoDBHealth.func1
        /src/vendor/kubedb.dev/mongodb/pkg/controller/health.go:66 +0x166
```
