### ISSUE TITLE
ES operator testing: health check issue

### ISSUE THREAD

**Issue by kamolhasan** [kubedb/project#834]

**Comment by kamolhasan** [comment]
I0520 13:26:46.432436       1 controller.go:113] Started processing, key: demo/es-9
E0520 13:26:46.460295       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 474 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x314afc0, 0x54abfa0)
	/src/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/src/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x86
panic(0x314afc0, 0x54abfa0)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
kubedb.dev/elasticsearch/pkg/controller.(*Controller).ensureAppBinding.func1(0xc000ca5a00, 0xc000ca5a00)
	/src/pkg/controller/appbinding.go:114 +0x485
kmodules.xyz/custom-resources/client/clientset/versioned/typed/appcatalog/v1alpha1/util.CreateOrPatchAppBinding(0x3b08328, 0xc0000d0028, 0x3ab8a50, 0xc000b83890, 0xc00196f7cc, 0x4, 0x0, 0x0, 0xc00196f7dc, 0x4, ...)
	/src/vendor/kmodules.xyz/custom-resources/client/clientset/versioned/typed/appcatalog/v1alpha1/util/appbinding.go:39 +0x4a4
kubedb.dev/elasticsearch/pkg/controller.(*Controller).ensureAppBinding(0xc0003ed200, 0xc001716000, 0xc001716000, 0x35fcaf0, 0x7, 0x0)
	/src/pkg/controller/appbinding.go:85 +0x778
kubedb.dev/elasticsearch/pkg/controller.(*Controller).create(0xc0003ed200, 0xc001716000, 0x2, 0x35fa7a2)
	/src/pkg/controller/elasticsearch.go:98 +0x61c
kubedb.dev/elasticsearch/pkg/controller.(*Controller).runElasticsearch(0xc0003ed200, 0xc0014009a0, 0x9, 0xc000ff6b70, 0xc000fd0d00)
	/src/pkg/controller/workqueue.go:164 +0xe6b
kmodules.xyz/client-go/tools/queue.(*Worker).processNextEntry(0xc001120f80, 0x203000)
	/src/vendor/kmodules.xyz/client-go/tools/queue/worker.go:84 +0xf7
kmodules.xyz/client-go/tools/queue.(*Worker).processQueue(...)
	/src/vendor/kmodules.xyz/client-go/tools/queue/worker.go:67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000fe0c50)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000fe0c50, 0x3aa2980, 0xc0012dc270, 0x1, 0xc0000ac540)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000fe0c50, 0x3b9aca00, 0x0, 0x1, 0xc0000ac540)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc000fe0c50, 0x3b9aca00, 0xc0000ac540)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by kmodules.xyz/client-go/tools/queue.(*Worker).Run
	/src/vendor/kmodules.xyz/client-go/tools/queue/worker.go:53 +0x89
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2c1c185]

goroutine 474 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/src/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x109
panic(0x314afc0, 0x54abfa0)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
kubedb.dev/elasticsearch/pkg/controller.(*Controller).ensureAppBinding.func1(0xc000ca5a00, 0xc000ca5a00)
	/src/pkg/controller/appbinding.go:114 +0x485
kmodules.xyz/custom-resources/client/clientset/versioned/typed/appcatalog/v1alpha1/util.CreateOrPatchAppBinding(0x3b08328, 0xc0000d0028, 0x3ab8a50, 0xc000b83890, 0xc00196f7cc, 0x4, 0x0, 0x0, 0xc00196f7dc, 0x4, ...)
	/src/vendor/kmodules.xyz/custom-resources/client/clientset/versioned/typed/appcatalog/v1alpha1/util/appbinding.go:39 +0x4a4
kubedb.dev/elasticsearch/pkg/controller.(*Controller).ensureAppBinding(0xc0003ed200, 0xc001716000, 0xc001716000, 0x35fcaf0, 0x7, 0x0)
	/src/pkg/controller/appbinding.go:85 +0x778
kubedb.dev/elasticsearch/pkg/controller.(*Controller).create(0xc0003ed200, 0xc001716000, 0x2, 0x35fa7a2)
	/src/pkg/controller/elasticsearch.go:98 +0x61c
kubedb.dev/elasticsearch/pkg/controller.(*Controller).runElasticsearch(0xc0003ed200, 0xc0014009a0, 0x9, 0xc000ff6b70, 0xc000fd0d00)
	/src/pkg/controller/workqueue.go:164 +0xe6b
kmodules.xyz/client-go/tools/queue.(*Worker).processNextEntry(0xc001120f80, 0x203000)
	/src/vendor/kmodules.xyz/client-go/tools/queue/worker.go:84 +0xf7
kmodules.xyz/client-go/tools/queue.(*Worker).processQueue(...)
	/src/vendor/kmodules.xyz/client-go/tools/queue/worker.go:67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000fe0c50)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000fe0c50, 0x3aa2980, 0xc0012dc270, 0x1, 0xc0000ac540)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000fe0c50, 0x3b9aca00, 0x0, 0x1, 0xc0000ac540)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc000fe0c50, 0x3b9aca00, 0xc0000ac540)
	/src/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
created by kmodules.xyz/client-go/tools/queue.(*Worker).Run
	/src/vendor/kmodules.xyz/client-go/tools/queue/worker.go:53 +0x89

**Comment by kamolhasan** [comment]
I0520 13:27:40.985659       1 run.go:41] Starting elasticsearch-server...
I0520 13:27:44.878569       1 controller.go:60] Initializing StatefulSet watcher.....
I0520 13:27:44.941491       1 lib.go:204] Kubernetes version: &version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:19:55Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
I0520 13:27:45.098472       1 controller.go:105] Ensuring CustomResourceDefinition...
W0520 13:27:50.334276       1 warnings.go:70] admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
W0520 13:27:50.425424       1 warnings.go:70] admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
W0520 13:27:50.433801       1 warnings.go:70] admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
W0520 13:27:50.444460       1 warnings.go:70] admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
I0520 13:27:50.452198       1 lib.go:221] License verification skipped
I0520 13:27:50.454806       1 controller.go:141] Starting KubeDB controller
I0520 13:27:50.543955       1 requestheader_controller.go:169] Starting RequestHeaderAuthRequestController
I0520 13:27:50.544007       1 shared_informer.go:240] Waiting for caches to sync for RequestHeaderAuthRequestController
I0520 13:27:50.545902       1 secure_serving.go:197] Serving securely on [::]:8443
I0520 13:27:50.553256       1 configmap_cafile_content.go:202] Starting client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I0520 13:27:50.553319       1 shared_informer.go:240] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I0520 13:27:50.553634       1 configmap_cafile_content.go:202] Starting client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I0520 13:27:50.553904       1 shared_informer.go:240] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I0520 13:27:50.557893       1 dynamic_serving_content.go:130] Starting serving-cert::/var/serving-cert/tls.crt::/var/serving-cert/tls.key
I0520 13:27:50.558204       1 tlsconfig.go:240] Starting DynamicServingCertificateController
I0520 13:27:50.645881       1 apf_controller.go:294] Starting API Priority and Fairness config controller
I0520 13:27:51.051659       1 shared_informer.go:247] Caches are synced for RequestHeaderAuthRequestController 
E0520 13:27:51.057326       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.StatefulSet: failed to list *v1.StatefulSet: Get "https://10.128.0.1:443/apis/apps/v1/statefulsets?limit=500&resourceVersion=0": http2: client connection force closed via ClientConn.Close
I0520 13:27:51.064556       1 shared_informer.go:247] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file 
I0520 13:27:51.154095       1 shared_informer.go:247] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::client-ca-file 
W0520 13:27:51.204853       1 reflector.go:436] kubedb.dev/apimachinery/client/informers/externalversions/factory.go:121: watch of *v1alpha2.Elasticsearch ended with: very short watch: kubedb.dev/apimachinery/client/informers/externalversions/factory.go:121: Unexpected watch close - watch lasted less than a second and no items received
W0520 13:27:51.205092       1 reflector.go:436] kubedb.dev/apimachinery/client/informers/externalversions/factory.go:121: watch of *v1alpha1.ElasticsearchVersion ended with: very short watch: kubedb.dev/apimachinery/client/informers/externalversions/factory.go:121: Unexpected watch close - watch lasted less than a second and no items received
E0520 13:27:51.205687       1 request.go:1027] Unexpected error when reading response body: read tcp 10.2.1.2:60740->10.128.0.1:443: read: connection reset by peer
E0520 13:27:51.205757       1 webhook.go:202] Failed to make webhook authorizer request: unexpected error when reading response body. Please retry. Original error: read tcp 10.2.1.2:60740->10.128.0.1:443: read: connection reset by peer
E0520 13:27:51.206147       1 errors.go:77] unexpected error when reading response body. Please retry. Original error: read tcp 10.2.1.2:60740->10.128.0.1:443: read: connection reset by peer
W0520 13:27:51.206284       1 reflector.go:436] k8s.io/client-go/informers/factory.go:134: watch of *v1beta1.PriorityLevelConfiguration ended with: very short watch: k8s.io/client-go/informers/factory.go:134: Unexpected watch close - watch lasted less than a second and no items received
W0520 13:27:51.206485       1 reflector.go:436] k8s.io/apiserver/pkg/server/dynamiccertificates/configmap_cafile_content.go:206: watch of *v1.ConfigMap ended with: very short watch: k8s.io/apiserver/pkg/server/dynamiccertificates/configmap_cafile_content.go:206: Unexpected watch close - watch lasted less than a second and no items received
W0520 13:27:51.206528       1 reflector.go:436] k8s.io/apiserver/pkg/server/dynamiccertificates/configmap_cafile_content.go:206: watch of *v1.ConfigMap ended with: very short watch: k8s.io/apiserver/pkg/server/dynamiccertificates/configmap_cafile_content.go:206: Unexpected watch close - watch lasted less than a second and no items received
W0520 13:27:51.206341       1 reflector.go:436] k8s.io/apiserver/pkg/authentication/request/headerrequest/requestheader_controller.go:172: watch of *v1.ConfigMap ended with: very short watch: k8s.io/apiserver/pkg/authentication/request/headerrequest/requestheader_controller.go:172: Unexpected watch close - watch lasted less than a second and no items received
I0520 13:27:51.246851       1 apf_controller.go:299] Running API Priority and Fairness config worker
I0520 13:27:52.055768       1 controller.go:113] Started processing, key: demo/es-7
I0520 13:27:52.056225       1 util.go:213] Looking for the Stash operator.......
I0520 13:27:52.057507       1 controller.go:113] Started processing, key: demo/es-6
I0520 13:27:52.058839       1 health.go:46] Starting Elasticsearch health checker...
W0520 13:27:52.151939       1 warnings.go:70] admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
W0520 13:27:52.243585       1 warnings.go:70] admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
W0520 13:27:52.292148       1 warnings.go:70] admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
W0520 13:27:52.389400       1 warnings.go:70] admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
W0520 13:27:52.627587       1 warnings.go:70] storage.k8s.io/v1beta1 StorageClass is deprecated in v1.19+, unavailable in v1.22+; use storage.k8s.io/v1 StorageClass
I0520 13:27:52.734015       1 controller.go:113] Started processing, key: demo/es-10
W0520 13:27:52.743793       1 warnings.go:70] storage.k8s.io/v1beta1 StorageClass is deprecated in v1.19+, unavailable in v1.22+; use storage.k8s.io/v1 StorageClass
I0520 13:27:52.750772       1 controller.go:113] Started processing, key: demo/es-8
I0520 13:27:52.840745       1 recorder.go:109] Event created:  kubedb-community.1680c95e5405b806
panic: Get "https://10.128.0.1:443/apis/apiregistration.k8s.io/v1beta1/apiservices/v1alpha1.validators.kubedb.com": write tcp 10.2.1.2:60714->10.128.0.1:443: write: broken pipe

goroutine 297 [running]:
kubedb.dev/elasticsearch/pkg/server.completedConfig.New.func2.1(0xc000812f90, 0xc00069b200, 0xc0009b1e00)
	/src/pkg/server/server.go:242 +0x546
created by kubedb.dev/elasticsearch/pkg/server.completedConfig.New.func2
	/src/pkg/server/server.go:212 +0x52
