### ISSUE TITLE
MySQL, BUG: Release v2022.02.22 panics with exsisting secret

### ISSUE THREAD

**Issue by heheh13** [kubedb/project#864]
- [X] fixed in the next release [pr](https://github.com/kubedb/mysql/pull/463)

KubeDB operator throws a nil pointer error if a database is created with an existing secret.

```
E0417 17:11:37.159930       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 1577 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x2f1c160?, 0x5b94750})
	/src/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x99
kmodules.xyz/client-go/tools/queue.(*Worker).panicSafeReconcile.func1()
	/src/vendor/kmodules.xyz/client-go/tools/queue/worker.go:119 +0x7a
panic({0x2f1c160, 0x5b94750})
	/usr/local/go/src/runtime/panic.go:838 +0x207
kubedb.dev/mysql/pkg/controller.(*Reconciler).upgradeAuthSecret(0xc00120f448?, 0xc0017b7500?)
	/src/vendor/kubedb.dev/mysql/pkg/controller/secret.go:244 +0x39
```

**Comment by tamalsaha** [comment]
Fixed!
